import type { Metadata } from "next"
import { Toaster } from "@/components/ui/sonner"
import {
  Geist,
  Geist_Mono,
  Bebas_Neue,
  Oswald,
  DM_Sans,
  Nunito_Sans,
} from "next/font/google"
import "./globals.css"
import { AuthProvider } from "@/context/use-auth"

// Geist Sans
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

// Geist Mono
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

// Bebas Neue (good for big titles)
const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: "400",
})

// Oswald (strong headings)
const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
})

// DM Sans (Spotify-like body text)
const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
})

// Nunito Sans (clean alternative body font)
const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Bakha Bazar",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="apple-mobile-web-app-title" content="BakhaBazar" />
      </head>
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${bebasNeue.variable} 
          ${oswald.variable} 
          ${dmSans.variable} 
          ${nunitoSans.variable} 
          antialiased
        `}
      >
        <AuthProvider>
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  )
}
